{
    "relation": [
        [
            "Author",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "David Schneider",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo",
            "Maciej Fijalkowski",
            "Antonio Cuni",
            "Antonio Cuni",
            "Armin Rigo",
            "Armin Rigo",
            "Armin Rigo"
        ],
        [
            "Commit",
            "a3cb049 M",
            "98d5562 M",
            "9ccaeaf",
            "6faba93",
            "2b4ea60",
            "20aac7a",
            "a44729d",
            "6359f7f",
            "e9e7c0e",
            "a53ca6d",
            "98ad343",
            "9439564",
            "8a07872",
            "33549b3",
            "a16fce4",
            "23bcf87",
            "d83d8fd",
            "326cd56 M",
            "6ab51a5",
            "0425648",
            "68e9165",
            "726f2b8",
            "e6204af",
            "b1d2b7c",
            "310d7cd",
            "7229a88 M",
            "b693c61",
            "ae05103",
            "922c4d3",
            "ac7ddb5"
        ],
        [
            "Message",
            "hg merge default",
            "hg merge out-of-line-guards-2",
            "Wrong. A test was present but failed on CPython 2.7 (with -A). Killed it, and replaced it with tests that check that even when making new frozen sets, the overridden __new__ is not called.",
            "More obscurity in the behavior of sets. It seems that in order to make new *frozen* sets, their possibly overridden __new__ must be called; but to make new *non-frozen* sets, it must not.",
            "Obscure workaround for cpyext. Fixes test_structseq.py, which has been failing since 6ee045ccb063. Blame new-dict-proxy devs for not running tests before merging...",
            "Fix test.",
            "Fix.",
            "The torrents are set up on wyvern for now, but writing explicit wyvern urls is probably wrong.",
            "Remove some more codespeak dependencies.",
            "Remove external reference to codespeak",
            "Adapt the _immutable_ and _immutable_fields_ hints left and right. I think this branch is now ready to be merged, if it passes all tests.",
            "Patch by qbproger: write square roots with the x86 SSE2 instruction SQRTSD. Also cleans up a bit the error checking around math.sqrt().",
            "Enable supports_floats by default also when running tests with interp_operations(), not just meta_interp(). Caused some amount of troubles to find out what was going on in the sqrtsd.patch.",
            "Patch by qbproger: seems to be needed on OpenSUSE for dlopen().",
            "Write a more detailed __repr__ for CallDescrs.",
            "remove static keyword from pypy_read_timestamp to match the definition in the header file",
            "Revert d5dd9462363a on model.py. I'm unsure why, but it seems that all tests are happily working now...",
            "merge heads",
            "Finish adapting to out-of-line-guards-2.",
            "Add a marker '<====' on the first line containing the difference.",
            "issue712 resolved Fix the test to conform to CPython's behavior (as tested with -A). Fix the code accordingly.",
            "Fix for the new ABORT_FORCE_QUASIIMMUT.",
            "Turn on CodeWriter.debug in the tests, printing the jitcodes.",
            "Correction: this test is not passing. Skip it for now, think about it later if the issue arises within pypy...",
            "remove old obscure unused files",
            "merge heads",
            "add a warning in case oprofile has been explicitly enabled but it is not found",
            "Updates to test_pypy_c_new.",
            "Updates to pypyjit.",
            "Another passing test"
        ],
        [
            "Labels",
            "Branches refactor-not-in-translator",
            "",
            "",
            "",
            "",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2",
            "",
            "",
            "",
            "Branches out-of-line-guards-2",
            "",
            "",
            "",
            "",
            "",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2",
            "",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2",
            "",
            "",
            "",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2",
            "Branches out-of-line-guards-2"
        ],
        [
            "Comments",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ],
        [
            "Approvals",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ],
        [
            "Date",
            "2011-05-08",
            "2011-05-08",
            "2011-05-08",
            "2011-05-08",
            "2011-05-08",
            "2011-05-07",
            "2011-05-07",
            "2011-05-07",
            "2011-05-07",
            "2011-05-07",
            "2011-05-07",
            "2011-05-07",
            "2011-05-07",
            "2011-05-07",
            "2011-05-06",
            "2011-05-06",
            "2011-05-06",
            "2011-05-06",
            "2011-05-06",
            "2011-05-06",
            "2011-05-06",
            "2011-05-06",
            "2011-05-06",
            "2011-05-05",
            "2011-05-06",
            "2011-05-05",
            "2011-05-05",
            "2011-05-04",
            "2011-05-04",
            "2011-05-04"
        ]
    ],
    "pageTitle": "tworing / pypy / Commits \u2014 Bitbucket",
    "title": "",
    "url": "https://bitbucket.org/tworing/pypy/commits/branch/refactor-not-in-translator",
    "hasHeader": true,
    "headerPosition": "FIRST_ROW",
    "tableType": "RELATION",
    "tableNum": 0,
    "s3Link": "common-crawl/crawl-data/CC-MAIN-2015-32/segments/1438042988598.68/warc/CC-MAIN-20150728002308-00021-ip-10-236-191-2.ec2.internal.warc.gz",
    "recordEndOffset": 850525367,
    "recordOffset": 850502848,
    "tableOrientation": "HORIZONTAL",
    "textBeforeTable": "",
    "textAfterTable": "Prev Next Blog",
    "hasKeyColumn": false,
    "keyColumnIndex": -1,
    "headerRowIndex": 0
}